[[redirects]]
	from = "https://eventstack-nl.netlify.com/*"
	to = "https://eventstack.nl/:splat"
	status = 301
	force = true

[[redirects]]
	from = "https://www.eventstack.nl/*"
	to = "https://eventstack.nl/:splat"
	status = 301
	force = true

[[redirects]]
	from = "/fronteersconf/calendar.ics"
	to = "https://airtable.com/shr4x0OSCQ5CekkrT/iCal?timeZone=Europe%2FAmsterdam&userLocale=en"
	status = 302
	force = true

[[headers]]
	for = "/*"

[headers.values]
	Content-Security-Policy = """
		default-src 'none'; \
		script-src 'self' 'unsafe-eval' *.cloudfront.net cdnjs.cloudflare.com polyfill.io apis.google.com rawgit.com; \
		style-src 'self' *.cloudfront.net fonts.googleapis.com; \
		img-src 'self' *.cloudfront.net dl.airtable.com *.googleusercontent.com blob:; \
		font-src 'self' fonts.gstatic.com; \
		connect-src 'self' api.eventstack.nl hooks.zapier.com api.airtable.com; \
		manifest-src 'self'; \
		frame-src accounts.google.com content.googleapis.com; \
		frame-ancestors 'none'; \
		form-action 'self' hooks.zapier.com; \
		upgrade-insecure-requests
		"""
	Referrer-Policy = "no-referrer-when-downgrade"
	Upgrade-Insecure-Requests = "1"
	X-Content-Type-Options = "nosniff"
	X-Frame-Options = "SAMEORIGIN"
	X-XSS-Protection = "1; mode=block"
