[build]
  command = "gulp"
  publish = "build"

[build.processing.html]
  pretty_urls = true

[[redirects]]
	from = "https://www.eventstack.nl/*"
	to = "https://eventstack.nl/:splat"
	status = 301
	force = true

[[headers]]
	for = "/"

	[headers.values]
	Content-Security-Policy = """
		default-src 'none'; \
		script-src 'self' 'unsafe-eval' *.cloudfront.net apis.google.com cdn.jsdelivr.net cdnjs.cloudflare.com polyfill.io rawgit.com; \
		style-src 'self' *.cloudfront.net fonts.googleapis.com; \
		img-src 'self' *.cloudfront.net *.googleusercontent.com dl.airtable.com blob:; \
		font-src 'self' fonts.gstatic.com; \
		connect-src 'self' api.airtable.com api.eventstack.nl hooks.zapier.com; \
		manifest-src 'self'; \
		frame-src accounts.google.com content.googleapis.com; \
		frame-ancestors 'none'; \
		form-action 'self' hooks.zapier.com; \
		upgrade-insecure-requests
		"""
	Referrer-Policy = "no-referrer-when-downgrade"
	Upgrade-Insecure-Requests = "1"
	X-Content-Type-Options = "nosniff"
	X-Frame-Options = "SAMEORIGIN"
	X-XSS-Protection = "1; mode=block"
