[[headers]]
	for = "/*"

[headers.values]
	Content-Security-Policy = """
		default-src 'none'; \
		script-src 'self' *.cloudfront.net cdnjs.cloudflare.com polyfill.io; \
		style-src 'self' *.cloudfront.net fonts.googleapis.com; \
		img-src 'self' *.cloudfront.net; \
		font-src 'self' fonts.gstatic.com; \
		connect-src 'self' api.eventstack.nl; \
		manifest-src 'self'; \
		frame-ancestors 'none'; \
		form-action 'self' hooks.zapier.com; \
		upgrade-insecure-requests
		"""
	Referrer-Policy = "no-referrer-when-downgrade"
	Upgrade-Insecure-Requests = "1"
	X-Content-Type-Options = "nosniff"
	X-Frame-Options = "SAMEORIGIN"
	X-XSS-Protection = "1; mode=block"
